Vest\SharedBundle\Entity\AppAnsichten:
    type: entity
    table: app_ansichten
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: ansicht_id
            generator:
                strategy: IDENTITY
    fields:
        anwendungId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: anwendung_id
        ansichtName:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: ansicht_name
        ansichtKurzname:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: ansicht_kurzname
        ansichtStatus:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            column: ansicht_status
        ansichtPrio:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: ansicht_prio
    manyToOne:
      anwendung:
        targetEntity: Vest\SharedBundle\Entity\AppAnwendungen
        inversedBy: ansichten
        joinColumn:
          name: anwendung_id
          referencedColumnName: anwendung_id
    lifecycleCallbacks: {  }
