Vest\SharedBundle\Entity\LzLizenzen:
    type: entity
    table: lz_lizenzen
    id:
        lizenzId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: lizenz_id
            generator:
                strategy: IDENTITY
    fields:
        anwendungId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: anwendung_id
        ansichtId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: ansicht_id
        lizenzName:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: lizenz_name
        lizenzBeschreibung:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: lizenz_beschreibung
        lizenzPreis:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: lizenz_preis
        typId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: typ_id
        lizenzKeysZeigen:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: lizenz_keys_zeigen
        lizenzEventCatId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: lizenz_event_cat_id
        lizenzEventMenge:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: lizenz_event_menge
        lizenzDauer:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            column: lizenz_dauer
        lizenzAbo:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: lizenz_abo
    lifecycleCallbacks: {  }
