Vest\SharedBundle\Entity\LzTypen:
    type: entity
    table: lz_typen
    id:
        typId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: typ_id
            generator:
                strategy: IDENTITY
    fields:
        typName:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: typ_name
    lifecycleCallbacks: {  }
