Vest\SharedBundle\Entity\NsGruppen:
    type: entity
    table: ns_gruppen
    id:
        newsGruppeId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: news_gruppe_id
            generator:
                strategy: IDENTITY
    fields:
        newsId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: news_id
        gruppeId:
            type: bigint
            nullable: true
            unsigned: false
            comment: ''
            column: gruppe_id
    lifecycleCallbacks: {  }
