Vest\SharedBundle\Entity\RbacRollenAddrPersonen:
    type: entity
    table: rbac_rollen_addr_personen
    id:
        rollePersonId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: rolle_person_id
            generator:
                strategy: IDENTITY
    fields:
        rolleId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: rolle_id
        personId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: person_id
    lifecycleCallbacks: {  }
