Vest\SharedBundle\Entity\RbacGruppen:
    type: entity
    table: rbac_gruppen
    id:
        gruppeId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: gruppe_id
            generator:
                strategy: IDENTITY
    fields:
        kontaktId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: kontakt_id
        gruppeTypId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: gruppe_typ_id
        gruppeZugriffsstufeId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: gruppe_zugriffsstufe_id
        gruppeName:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: gruppe_name
        gruppeBeschreibung:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: gruppe_beschreibung
        gruppeParentId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: gruppe_parent_id
        gruppeKontaktspezifisch:
            type: boolean
            nullable: false
            comment: ''
            column: gruppe_kontaktspezifisch
        gruppeLizenzspezifisch:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: gruppe_lizenzspezifisch
        gruppeEssentiell:
            type: boolean
            nullable: false
            comment: ''
            column: gruppe_essentiell
        gruppeSchutz:
            type: boolean
            nullable: false
            comment: ''
            column: gruppe_schutz
    manyToMany:
      kontakte:
        targetEntity: Vest\SharedBundle\Entity\AddrKontakte
        mappedBy: gruppen
      personen:
        targetEntity: Vest\SharedBundle\Entity\AddrPersonen
        mappedBy: gruppen

      rollen:
        targetEntity: Vest\SharedBundle\Entity\RbacRollen
        inversedBy: gruppen
        joinTable:
          name: rbac_gruppen_rbac_rollen
          joinColumns:
            gruppe_id:
              referencedColumnName: gruppe_id
          inverseJoinColumns:
            rolle_id:
              referencedColumnName: rolle_id
    lifecycleCallbacks: {  }
