Vest\SharedBundle\Entity\RbacGruppenZugriffstufen:
    type: entity
    table: rbac_gruppen_zugriffstufen
    id:
        gruppeZugriffsstufeId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: gruppe_zugriffsstufe_id
            generator:
                strategy: IDENTITY
    fields:
        gruppeZugriffsstufeName:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: gruppe_zugriffsstufe_name
        gruppeZugriffsstufeBeschreibung:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: gruppe_zugriffsstufe_beschreibung
    lifecycleCallbacks: {  }
