Vest\SharedBundle\Entity\RbacRollenRbacRechte:
    type: entity
    table: rbac_rollen_rbac_rechte
    uniqueConstraints:
        rollen_rechte_id:
            columns:
                - rollen_rechte_id
    id:
        rollenRechteId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: rollen_rechte_id
            generator:
                strategy: IDENTITY
    fields:
        rolleId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: rolle_id
        rechtId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: recht_id
    lifecycleCallbacks: {  }
