Vest\SharedBundle\Entity\RbacGruppenAddrKontakte:
    type: entity
    table: rbac_gruppen_addr_kontakte
    id:
        gruppeKontaktId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: gruppe_kontakt_id
            generator:
                strategy: IDENTITY
    fields:
        gruppeId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: gruppe_id
        kontaktId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: kontakt_id
        kontaktspezifischId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: kontaktspezifisch_id
    lifecycleCallbacks: {  }
