Vest\SharedBundle\Entity\Resfrage:
    type: entity
    table: resfrage
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: u_id
        frage:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        prio:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        auswertungsbereich:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        type:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
