Vest\SharedBundle\Entity\ShopNummernkreisTypen:
    type: entity
    table: shop_nummernkreis_typen
    id:
        nummernkreisTypId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: nummernkreis_typ_id
            generator:
                strategy: IDENTITY
    fields:
        nummernkreisTypName:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: nummernkreis_typ_name
        nummernkreisTypPlatzhalter:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
            column: nummernkreis_typ_platzhalter
    lifecycleCallbacks: {  }
