Vest\SharedBundle\Entity\ShopVersandarten:
    type: entity
    table: shop_versandarten
    id:
        versandartId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: versandart_id
            generator:
                strategy: IDENTITY
    fields:
        versandartName:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: versandart_name
    lifecycleCallbacks: {  }
