Vest\SharedBundle\Entity\ShopBestellungProdukte:
    type: entity
    table: shop_bestellung_produkte
    indexes:
        fk_shop_bestellung_produkte_shop_produkte1:
            columns:
                - produkt_id
        fk_shop_bestellung_produkte_shop_bestellungen1:
            columns:
                - bestell_id
        fk_shop_bestellung_produkte_shop_termine1:
            columns:
                - termin_id
    id:
        bestellungProduktId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: bestellung_produkt_id
            generator:
                strategy: IDENTITY
    fields:
        produktId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: produkt_id
        bestellId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: bestell_id
        terminId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: termin_id
        personId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: person_id
        produktPreis:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: produkt_preis
        produktMenge:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: produkt_menge
        produktGesamtPreis:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: produkt_gesamt_preis
    lifecycleCallbacks: {  }
