Vest\SharedBundle\Entity\ShopProdukteZahlarten:
    type: entity
    table: shop_produkte_zahlarten
    indexes:
        fk_shop_produkte_zahlarten_shop_zahlarten1:
            columns:
                - zahlart_id
        fk_shop_produkte_zahlarten_shop_produkte1:
            columns:
                - produkt_id
    id:
        produktZahlartId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: produkt_zahlart_id
            generator:
                strategy: IDENTITY
    fields:
        produktId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: produkt_id
        zahlartId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: zahlart_id
    lifecycleCallbacks: {  }
