Vest\SharedBundle\Entity\ShopKategorienAttribute:
    type: entity
    table: shop_kategorien_attribute
    id:
        kategorieAttributId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: kategorie_attribut_id
            generator:
                strategy: IDENTITY
    fields:
        kategorieId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: kategorie_id
        attributId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: attribut_id
    lifecycleCallbacks: {  }
