Vest\SharedBundle\Entity\ShopAttribute:
    type: entity
    table: shop_attribute
    id:
        attributId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: attribut_id
            generator:
                strategy: IDENTITY
    fields:
        attributName:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: attribut_name
        attributDefault:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: attribut_default
        attributStatus:
            type: boolean
            nullable: true
            comment: ''
            default: '1'
            column: attribut_status
    lifecycleCallbacks: {  }
