Vest\SharedBundle\Entity\ShopBestellungen:
    type: entity
    table: shop_bestellungen
    id:
        bestellungId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: bestellung_id
            generator:
                strategy: IDENTITY
    fields:
        bestellerKontaktId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: besteller_kontakt_id
        bestellerPersonId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: besteller_person_id
        bestellDatum:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: bestell_datum
        lieferName:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: liefer_name
        lieferVorname:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: liefer_vorname
        lieferNachname:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: liefer_nachname
        lieferStrasse:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: liefer_strasse
        lieferPlz:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: liefer_plz
        lieferOrt:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: liefer_ort
        rechnungName:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: rechnung_name
        rechnungVorname:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: rechnung_vorname
    lifecycleCallbacks: {  }
