Vest\SharedBundle\Entity\ShopKategorienZahlarten:
    type: entity
    table: shop_kategorien_zahlarten
    indexes:
        fk_shop_kategorie_zahlarten_shop_kategorien1:
            columns:
                - kategorie_id
        fk_shop_kategorie_zahlarten_shop_zahlarten1:
            columns:
                - zahlart_id
    id:
        kategorieZahlartId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: kategorie_zahlart_id
            generator:
                strategy: IDENTITY
    fields:
        kategorieId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: kategorie_id
        zahlartId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: zahlart_id
    lifecycleCallbacks: {  }
