Vest\SharedBundle\Entity\ShopTermineAttribute:
    type: entity
    table: shop_termine_attribute
    indexes:
        fk_shop_termine_attribute_shop_termine1:
            columns:
                - termin_id
        fk_shop_termine_attribute_shop_attribute1:
            columns:
                - attribut_id
    id:
        terminAttribut:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: termin_attribut
            generator:
                strategy: IDENTITY
    fields:
        terminId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: termin_id
        attributId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: attribut_id
        value:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
