Vest\SharedBundle\Entity\ShopZahlartenEinstellungen:
    type: entity
    table: shop_zahlarten_einstellungen
    indexes:
        fk_shop_zahlarten_einstellungen_shop_zahlarten1:
            columns:
                - zahlart_id
    id:
        zahlartEinstellungId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: zahlart_einstellung_id
            generator:
                strategy: IDENTITY
    fields:
        zahlartId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: zahlart_id
        zahlartApiBenutzer:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: zahlart_api_benutzer
        zahlartApiPasswort:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: zahlart_api_passwort
        zahlartApiSignatur:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: zahlart_api_signatur
    lifecycleCallbacks: {  }
