Vest\SharedBundle\Entity\TestFkT1:
    type: entity
    table: test_fk_t1
    id:
        pk:
            type: boolean
            nullable: false
            comment: ''
            id: true
            column: PK
            generator:
                strategy: IDENTITY
    fields:
        wert:
            type: string
            nullable: false
            length: 8000
            fixed: false
            comment: ''
            column: WERT
        wert001:
            type: string
            nullable: false
            length: 8000
            fixed: false
            comment: ''
            column: WERT_001
    lifecycleCallbacks: {  }
