Vest\SharedBundle\Entity\UfAntworten:
    type: entity
    table: uf_antworten
    id:
        antwortId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: antwort_id
            generator:
                strategy: IDENTITY
    fields:
        frageId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: frage_id
        kontaktId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: kontakt_id
        antwortWert:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: antwort_wert
        antwortBenutzerdefiniert:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: antwort_benutzerdefiniert
        antwortBenutzerdefiniert2:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: antwort_benutzerdefiniert2
        datumId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: datum_id
        personId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: person_id
        eventTag:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: event_tag
        antwortToken:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: antwort_token
        antwortDatum:
            type: datetime
            nullable: false
            comment: ''
            column: antwort_datum
    lifecycleCallbacks: {  }
