Vest\SharedBundle\Entity\VaVeranstaltungen:
    type: entity
    table: va_veranstaltungen
    id:
        veranstaltungId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: veranstaltung_id
            generator:
                strategy: IDENTITY
    fields:
        veranstaltungTag:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: veranstaltung_tag
        veranstaltungName:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: veranstaltung_name
        veranstaltungBeschreibung:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: veranstaltung_beschreibung
        kontaktId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: kontakt_id
        kategorieId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '1'
            column: kategorie_id
        veranstaltungPdfOrder:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: veranstaltung_pdf_order
        veranstaltungtIstpres:
            type: integer
            nullable: false
            unsigned: false
            comment: Präsentation
            column: veranstaltungt_istpres
        veranstaltungTipp:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            column: veranstaltung_tipp
        veranstaltungNeu:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            column: veranstaltung_neu
    lifecycleCallbacks: {  }
