Vest\SharedBundle\Entity\VaVeranstaltungenRbacGruppen:
    type: entity
    table: va_veranstaltungen_rbac_gruppen
    id:
        veranstaltungGruppeId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: veranstaltung_gruppe_id
            generator:
                strategy: IDENTITY
    fields:
        veranstaltungenTag:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: veranstaltungen_tag
        gruppeId:
            type: bigint
            nullable: true
            unsigned: false
            comment: ''
            column: gruppe_id
    lifecycleCallbacks: {  }
