Formular-add:
    pattern:  /form/
    defaults: { _controller: VestResponsaBundle:Formular:index }
Formular-edit:
    pattern:  /form/{id}
    defaults: { _controller: VestResponsaBundle:Formular:index }
Formular-save:
    pattern:  /form/save
    defaults: { _controller: VestResponsaBundle:Formular:save }
task_success:
    pattern:  /form/erfolg{ergebnis}
    defaults: { _controller: VestResponsaBundle:Formular:erfolg }
task_fail:
    pattern:  /form/fail{ergebnis}
    defaults: { _controller: VestResponsaBundle:Formular:erfolg }
    
AddrPerson-add:
    pattern:  /person/
    defaults: { _controller: VestResponsaBundle:AddrPerson:index }
AddrPerson-edit:
    pattern:  /person/{id}
    defaults: { _controller: VestResponsaBundle:AddrPerson:index }
AddrPerson-save:
    pattern:  /person/save/
    defaults: { _controller: VestResponsaBundle:AddrPerson:save }

Security_login:
    pattern:  /responsa/login/
    defaults: { _controller: VestResponsaBundle:Login:Login }
Security_log-me-in:
    pattern:  /responsa/login/check/
    defaults: { _controller: VestResponsaBundle:Login:logincheck }
Security_Session:
    pattern:  /responsa/session/
    defaults: { _controller: VestResponsaBundle:Login:sessioncheck	 }
Security_logout:
    pattern:  /responsa/logout/
    defaults: { _controller: VestResponsaBundle:Base:Logout	 }


Responsa_default:
    pattern:  /responsa/
    defaults: { _controller: VestResponsaBundle:Umfrage:overview	 }

Responsa_overview:
    pattern:  /responsa/overview/
    defaults: { _controller: VestResponsaBundle:Umfrage:overview	 }
Responsa_new:
    pattern:  /responsa/new/
    defaults: { _controller: VestResponsaBundle:Umfrage:new	 }
Responsa_save:
    pattern:  /responsa/save/{id}
    defaults: { _controller: VestResponsaBundle:Umfrage:save	 }
Responsa_edit:
    pattern:  /responsa/edit/{id}
    defaults: { _controller: VestResponsaBundle:Umfrage:new, id: 0 }
Responsa_delete:
    pattern:  /responsa/delete/{u_id}
    defaults: { _controller: VestResponsaBundle:Umfrage:delete }

Responsa_frage_overview:
    pattern:  /responsa/frage/overview/{u_id}
    defaults: { _controller: VestResponsaBundle:Frage:overview	 }
Responsa_frage_new:
    pattern:  /responsa/frage/new/{u_id}
    defaults: { _controller: VestResponsaBundle:Frage:new	 }
Responsa_frage_save:
    pattern:  /responsa/frage/save/{u_id}.{id}
    defaults: { _controller: VestResponsaBundle:Frage:save	 }
Responsa_frage_edit:
    pattern:  /responsa/frage/edit/{u_id}.{id}
    defaults: { _controller: VestResponsaBundle:Frage:new, id: 0 }
Responsa_frage_delete:
    pattern:  /responsa/frage/delete/{f_id}.{u_id}
    defaults: { _controller: VestResponsaBundle:Frage:delete}


Responsa_antwort_overview:
    pattern:  /responsa/antwort/overview/{f_id}
    defaults: { _controller: VestResponsaBundle:Antwort:overview	 }
Responsa_antwort_alloverview:
    pattern:  /responsa/antwort/overview_all/{u_id}
    defaults: { _controller: VestResponsaBundle:Antwort:alloverview	 }

Responsa_view_show:
    pattern:  /responsa/view/show/{u_id}.{feld1}.{feld2}.{feld3}.{feld4}.{feld5}
    defaults: { _controller: VestResponsaBundle:ViewPublic:show, feld1:- , feld2: - , feld3: - , feld4: - , feld5: -   }
Responsa_view_erhalten:
    pattern:  /responsa/view/erhalten/{u_id}.{feld1}.{feld2}.{feld3}.{feld4}.{feld5}.{token}
    defaults: { _controller: VestResponsaBundle:ViewPublic:erhalten, feld1:- , feld2: - , feld3: - , feld4: - , feld5: -  }

Responsa_help:
    pattern:  /responsa/help/
    defaults: { _controller: VestResponsaBundle:Help:overview }
Responsa_Auswertung:
    pattern:  /responsa/auswertung/
    defaults: { _controller: VestResponsaBundle:Auswertung:overview }


Responsa_generate_show:
    pattern:  /responsa/generate/show/
    defaults: { _controller: VestResponsaBundle:View:generate }
Responsa_generate_erhalten:
    pattern:  /responsa/generate/erhalten/
    defaults: { _controller: VestResponsaBundle:View:GenerateErhahlten }


Profil_show:
    pattern:  /responsa/profil/show/
    defaults: { _controller: VestResponsaBundle:Profil:Overview,}
Profil_save:
    pattern:  /responsa/profil/save/
    defaults: { _controller: VestResponsaBundle:Profil:Save}