parameters:
    user_provider.class: Vest\ResponsaBundle\Security\User\UserProvider

services:
#    vest_symfony.example:
#        class: %vest_symfony.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    user_provider:
        class: "%user_provider.class%"
