imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"


# Assetic Configuration
#assetic:
#    debug:          "%kernel.debug%"
#    use_controller: false
#    bundles:        [ VestSymfonyBundle ]
    #java: /usr/bin/java
#    filters:
#        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"


assetic:
  java: java
  filters:
    cssembed:
      jar: '%kernel.root_dir%/Resources/java/cssembed-0.4.5.jar'
    yui_js:
      jar: '%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar'
    lessphp:
      file: '%kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php'
      apply_to: "\.less$"
  assets:
    jquery_js:
        inputs:
            - '%kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.2.js'
        filters: [?yui_js]
    bootstrap_js:
        inputs:
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/transition.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/alert.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/modal.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/dropdown.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/scrollspy.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/tab.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/tooltip.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/popover.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/button.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/collapse.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/carousel.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/affix.js'
        filters: [?yui_js]
    turbulence_js:
        inputs:
            - '%kernel.root_dir%/../src/Vest/SharedBundle/Resources/jscss/scripts/vendor/modernizr.js'
            - '%kernel.root_dir%/../src/Vest/SharedBundle/Resources/jscss/scripts/main.js'
            - '%kernel.root_dir%/../src/Vest/SharedBundle/Resources/jscss/scripts/turbulence/common.js'
            - '%kernel.root_dir%/../src/Vest/SharedBundle/Resources/jscss/scripts/turbulence/main-nav.js'
            - '%kernel.root_dir%/../src/Vest/SharedBundle/Resources/jscss/scripts/turbulence/user-nav.js'
            - '%kernel.root_dir%/../src/Vest/SharedBundle/Resources/jscss/scripts/turbulence/sidebar.js'
            - '%kernel.root_dir%/../src/Vest/SharedBundle/Resources/jscss/scripts/turbulence/tables.js'
            - '%kernel.root_dir%/../src/Vest/SharedBundle/Resources/jscss/scripts/vendor/jquery.jstree.js'
            - '%kernel.root_dir%/../src/Vest/SharedBundle/Resources/jscss/scripts/vendor/jquery.dataTables.min.js'
            - '%kernel.root_dir%/../src/Vest/SharedBundle/Resources/jscss/scripts/vendor/datatables.js'
            - '%kernel.root_dir%/../src/Vest/SharedBundle/Resources/jscss/scripts/vendor/select2.min.js'
        filters: [?yui_js]
    bootstrap_less:
        inputs:
            - '%kernel.root_dir%/../src/Vest/SharedBundle/Resources/jscss/less/bootstrap.less'
        filters: [lessphp,cssembed]
    turbulence_less:
        inputs:
            - '%kernel.root_dir%/../src/Vest/SharedBundle/Resources/jscss/less/proton.less'
        filters: [lessphp,cssembed]
    bootstrap_css:
            inputs:
                - '%kernel.root_dir%/../src/Vest/SharedBundle/Resources/jscss/less/bootstrap.css'
            filters: [cssembed]
    turbulence_css:
        inputs:
            - '%kernel.root_dir%/../src/Vest/SharedBundle/Resources/jscss/less/proton.css'
        filters: [cssembed]







# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
