security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    encoders:
        Vest\SymfonyUserBundle\Security\Entity\AddrPersonen: sha512

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        datenbank:
            id: user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false


        demo_secured_area:
            pattern:    ^/(person/test*|login_check)
            form_login:
                check_path: user_provider
                login_path: /sicher/login
            logout:
                path:    /sicher/logout
                target:  /
        login_firewall:
            pattern:  ^/person/login$
            anonymous: ~
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/person, roles: ROLE_ADMIN }