vest_symfony_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: VestSymfonyBundle:Default:index }
    
Formular-add:
    pattern:  /form/
    defaults: { _controller: VestSymfonyBundle:Formular:index }
Formular-edit:
    pattern:  /form/{id}
    defaults: { _controller: VestSymfonyBundle:Formular:index }
Formular-save:
    pattern:  /form/save
    defaults: { _controller: VestSymfonyBundle:Formular:save }
task_success:
    pattern:  /form/erfolg{ergebnis}
    defaults: { _controller: VestSymfonyBundle:Formular:erfolg }
task_fail:
    pattern:  /form/fail{ergebnis}
    defaults: { _controller: VestSymfonyBundle:Formular:erfolg } 
    
AddrPerson-add:
    pattern:  /person/
    defaults: { _controller: VestSymfonyBundle:AddrPerson:index }   
AddrPerson-edit:
    pattern:  /person/{id}
    defaults: { _controller: VestSymfonyBundle:AddrPerson:index }   
AddrPerson-save:
    pattern:  /person/save/
    defaults: { _controller: VestSymfonyBundle:AddrPerson:save }  

Security_login:
    pattern:  /login/
    defaults: { _controller: VestSymfonyBundle:Login:login }  
Security_log-me-in:
    pattern:  /login/check/
    defaults: { _controller: VestSymfonyBundle:Login:logincheck } 
Security_Session:
    pattern:  /session/
    defaults: { _controller: VestSymfonyBundle:Login:sessioncheck	 } 
Security_logout:
    pattern:  /logout/
    defaults: { _controller: VestSymfonyBundle:Login:logout	 }


Responsa_overview:
    pattern:  /responsa/overview/
    defaults: { _controller: VestSymfonyBundle:Umfrage:overview	 } 		
Responsa_new:
    pattern:  /responsa/new/
    defaults: { _controller: VestSymfonyBundle:Umfrage:new	 } 	
Responsa_save:
    pattern:  /responsa/save/{id}
    defaults: { _controller: VestSymfonyBundle:Umfrage:save	 } 
Responsa_edit:
    pattern:  /responsa/edit/{id}
    defaults: { _controller: VestSymfonyBundle:Umfrage:new, id: 0 } 

Responsa_frage_overview:
    pattern:  /responsa/frage/overview/{u_id}
    defaults: { _controller: VestSymfonyBundle:Frage:overview	 } 		
Responsa_frage_new:
    pattern:  /responsa/frage/new/{u_id}
    defaults: { _controller: VestSymfonyBundle:Frage:new	 } 	
Responsa_frage_save:
    pattern:  /responsa/frage/save/{u_id}.{id}
    defaults: { _controller: VestSymfonyBundle:Frage:save	 } 
Responsa_frage_edit:
    pattern:  /responsa/frage/edit/{u_id}.{id}
    defaults: { _controller: VestSymfonyBundle:Frage:new, id: 0 } 


Responsa_antwort_overview:
    pattern:  /responsa/antwort/overview/{f_id}
    defaults: { _controller: VestSymfonyBundle:Antwort:overview	 } 	
Responsa_antwort_alloverview:
    pattern:  /responsa/antwort/overview_all/{u_id}
    defaults: { _controller: VestSymfonyBundle:Antwort:alloverview	 } 	

Responsa_view_show:
    pattern:  /responsa/view/show/{u_id}.{feld1}.{feld2}.{feld3}.{feld4}.{feld5}
    defaults: { _controller: VestSymfonyBundle:View:show } 	
Responsa_view_erhalten:
    pattern:  /responsa/view/erhalten/{u_id}
    defaults: { _controller: VestSymfonyBundle:View:show } 	