parameters:
#    vest_symfony.example.class: Vest\SymfonyBundle\Example

services:
#    vest_symfony.example:
#        class: %vest_symfony.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
