Vest\SymfonyBundle\Entity\AddrPersonen: 
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:  
            fields: personEmail
            message: 'Es gibt bereits eine Person mit der EMail'
    properties:
        kontaktId:    
            - NotBlank: ~
        personAnrede:    
            - Choice: { choices: [herr, frau]}
        personTitel:     
        personVorname:    
            - NotBlank: ~
        personName:      
            - NotBlank: ~
        personBriefanrede:
        personZhanrede:  
        personTelefon:   
            - NotBlank: ~
        personEmail:     
            - NotBlank: ~  
            - Email: ~
        personMobil:     
        personPass:      
            - NotBlank: ~
        personAktualisiert:
        recordStatus:    
        personId:        