Vest\ResponsaBundle\Entity\AddrZusatzinfos:
    type: entity
    table: addr_zusatzinfos
    id:
        zusatzinfoId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: zusatzinfo_id
            generator:
                strategy: IDENTITY
    fields:
        zusatzinfoName:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: zusatzinfo_name
        elementId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: element_id
        zusatzinfoPflicht:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: zusatzinfo_pflicht
        validierungId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: validierung_id
    lifecycleCallbacks: {  }
