Vest\ResponsaBundle\Entity\AppAnwendungenRbacRollen:
    type: entity
    table: app_anwendungen_rbac_rollen
    id:
        anwendungenRollenId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: anwendungen_rollen_id
            generator:
                strategy: IDENTITY
    fields:
        anwendungId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: anwendung_id
        rolleId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: rolle_id
    lifecycleCallbacks: {  }
