Vest\ResponsaBundle\Entity\AppAnwendungen:
    type: entity
    table: app_anwendungen
    id:
        anwendungId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: anwendung_id
            generator:
                strategy: IDENTITY
    fields:
        anwendungName:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: anwendung_name
        anwendungBeschreibung:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: anwendung_beschreibung
        anwendungKurzname:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: anwendung_kurzname
        anwendungUberId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: anwendung_uber_id
        anwendungAnzeigePrio:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: anwendung_anzeige_prio
        anwendungFarbcode:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: anwendung_farbcode
        anwendungIcon:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: anwendung_icon
    lifecycleCallbacks: {  }
