Vest\ResponsaBundle\Entity\NsNews:
    type: entity
    table: ns_news
    id:
        newsId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: news_id
            generator:
                strategy: IDENTITY
    fields:
        newsName:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: news_name
        newsDatum:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: news_datum
        newsTeaser:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: news_teaser
        newsUrl:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: news_url
        kontaktId:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: kontakt_id
    lifecycleCallbacks: {  }
