Vest\ResponsaBundle\Entity\RbacRollen:
    type: entity
    table: rbac_rollen
    id:
        rolleId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: rolle_id
            generator:
                strategy: IDENTITY
    fields:
        kontaktId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: kontakt_id
        rolleName:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: rolle_name
        rolleBeschreibung:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: rolle_beschreibung
        rolleParentId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: rolle_parent_id
        rolleKontaktspezifisch:
            type: boolean
            nullable: false
            comment: ''
            column: rolle_kontaktspezifisch
        rolleLizenzspezifisch:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: rolle_lizenzspezifisch
        rolleEssentiell:
            type: boolean
            nullable: false
            comment: ''
            column: rolle_essentiell
        rolleSchutz:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: rolle_schutz
    lifecycleCallbacks: {  }
