Vest\ResponsaBundle\Entity\RbacGruppenAddrPersonen:
    type: entity
    table: rbac_gruppen_addr_personen
    id:
        gruppePersonId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: gruppe_person_id
            generator:
                strategy: IDENTITY
    fields:
        gruppeId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: gruppe_id
        personId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: person_id
        kontaktspezifischId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: kontaktspezifisch_id
    lifecycleCallbacks: {  }
