Vest\ResponsaBundle\Entity\SaleRabatte:
    type: entity
    table: sale_rabatte
    id:
        rabattId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: rabatt_id
            generator:
                strategy: IDENTITY
    fields:
        rabattName:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: rabatt_name
        rabattBeschreibung:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: rabatt_beschreibung
        kontaktId:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: kontakt_id
        rabatttypId:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: rabatttyp_id
    lifecycleCallbacks: {  }
