Vest\ResponsaBundle\Entity\ShopTermine:
    type: entity
    table: shop_termine
    indexes:
        fk_shop_termine_shop_produkte1:
            columns:
                - produkt_id
    id:
        terminId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: termin_id
            generator:
                strategy: IDENTITY
    fields:
        produktId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: produkt_id
        terminStart:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: termin_start
        personId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: person_id
        raumId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: raum_id
        webinarlizenzId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: webinarlizenz_id
    lifecycleCallbacks: {  }
