Vest\ResponsaBundle\Entity\ShopNummernkreise:
    type: entity
    table: shop_nummernkreise
    id:
        nummernkreisId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: nummernkreis_id
            generator:
                strategy: IDENTITY
    fields:
        kontaktId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: kontakt_id
        nummernkreisTypId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: nummernkreis_typ_id
        nummernkreisWert:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: nummernkreis_wert
        nummernkreisFormat:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: nummernkreis_format
    lifecycleCallbacks: {  }
