Vest\ResponsaBundle\Entity\ShopKategorien:
    type: entity
    table: shop_kategorien
    id:
        kategorieId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: kategorie_id
            generator:
                strategy: IDENTITY
    fields:
        kategorieName:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: kategorie_name
        kategorieStatus:
            type: boolean
            nullable: true
            comment: ''
            default: '1'
            column: kategorie_status
    lifecycleCallbacks: {  }
