Vest\ResponsaBundle\Entity\TestPersonenZusatz:
    type: entity
    table: test_personen_zusatz
    uniqueConstraints:
        INDEX_PZ_PERSON:
            columns:
                - personen_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 8000
            fixed: false
            comment: ''
            column: NAME
    manyToOne:
        testpersonen:
            targetEntity: TestPersonen
            cascade: {  }
            mappedBy: null
            inversedBy: testpersonenzusatz
            joinColumns:
                personen_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
