Vest\ResponsaBundle\Entity\VaAnmeldungen:
    type: entity
    table: va_anmeldungen
    id:
        anmeldungId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: anmeldung_id
            generator:
                strategy: IDENTITY
    fields:
        personId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: person_id
        event:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
        datumId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: datum_id
        flatrateId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: flatrate_id
        anmeldungenBesuch:
            type: boolean
            nullable: false
            comment: ''
            column: anmeldungen_besuch
        anmeldungenIsreg:
            type: boolean
            nullable: false
            comment: ''
            column: anmeldungen_isReg
    lifecycleCallbacks: {  }
