Vest\ResponsaBundle\Entity\VaCodes:
    type: entity
    table: va_codes
    id:
        eventCodesId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: event_codes_id
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: user_id
        eventCodeValue:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: event_code_value
        veranstaltungTag:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: veranstaltung_tag
        datumId:
            type: bigint
            nullable: true
            unsigned: false
            comment: ''
            column: datum_id
    lifecycleCallbacks: {  }
